version: "3.8"
services:
    db_docker_symfony:
        image: 'mariadb:10.5.10'
        container_name: db_docker_symfony
        volumes:
            - db-defautSymfonyApli:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        ports:
            # To allow the host machine to access the ports below, modify the lines below.
            # For example, to allow the host to connect to port 3306 on the container, you would change
            # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
            # See https://docs.docker.com/compose/compose-file/#ports for more information.
            - '3306:3306'
        restart: always
        networks:
            - dev


    phpmyadmin_docker_symfony:
        image: phpmyadmin
        container_name: phpmyadmin_docker_symfony
        restart: always
        depends_on:
            - db_docker_symfony
        ports:
            - 8080:80
        environment:
            PMA_HOST: db_docker_symfony
            UPLOAD_LIMIT: 300M
        networks:
            - dev

networks:
    dev:

volumes: 
    db-defautSymfonyApli:
        external: true
        name: bdd_db-defautSymfonyApli